### ISSUE TITLE
Used reaction highlight not visible

### ISSUE THREAD

**Issue by ronneycz** [FlurryShy/DiscordDeBrand#1]
I loaded this theme in Vesktop and noticed that when you put a reaction to a message, no highlight of it shows up. That makes it hard to see if you've used a reaction on a server message where multiple members have used multiple reactions, for example.

I also wanna say, please keep this theme up to date, I couldn't find any other revert theme as up to date as yours. The new "blurple" especially is terrible to look at.

**Comment by FlurryShy** [comment]
was never really meant to be a "public" theme - or rather never thought anyone would find it.
glad you like it. the code is a mess and I need to re-do a lot of things  though.

and I agree. the "blurple" is eye-bleed-blue to my eyes. it gives me literal headaches... which is why I keep updating this theme.

fixed the issue, the background should be different after a reload of the theme.
![image](https://github.com/FlurryShy/DiscordDeBrand/assets/84310339/f07f5c55-5041-4bff-bfe8-8f1ac0a08a65)
